<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
    <name>Test Suite 15052025</name>
    <description></description>
    <tag></tag>
    <isRerun>false</isRerun>
    <mailRecipient></mailRecipient>
    <numberOfRerun>3</numberOfRerun>
    <pageLoadTimeout>30</pageLoadTimeout>
    <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
    <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
    <rerunImmediately>true</rerunImmediately>
    <testSuiteGuid>31859278-79ce-40b9-ac08-95096df0830f</testSuiteGuid>
    <testCaseLink>
        <guid>f62d0a56-de19-4aa0-855a-b7ab66741e06</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Feature Test Cases/Verify the application logs out the user after 15 minutes of inactivity</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
    </testCaseLink>
    <testCaseLink>
        <guid>c9713516-c1e1-49d9-8aa9-ae199da0ba38</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Feature Test Cases/Verify that data entered in a form is correctly saved and displayed after submission</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>269060e5-49c4-4771-af87-4bebef169502</variableId>
        </variableLink>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>bf303a06-fe36-4a87-b581-5dbfb9794c78</variableId>
        </variableLink>
    </testCaseLink>
    <testCaseLink>
        <guid>d4571f62-8fcb-4b69-b491-760b001b6dca</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Common Test Cases/Verify the user is able to log in with valid credentials (1)</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>14d98e7b-4ac8-4e28-8ce7-394001d188f0</variableId>
        </variableLink>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>a97344e7-5f9c-4936-92a2-d85e5463f3c9</variableId>
        </variableLink>
    </testCaseLink>
    <testCaseLink>
        <guid>6319d6c1-c486-4414-915f-d964d9c2adcf</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Common Test Cases/Verify the user is able to log in with valid credentials</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>14d98e7b-4ac8-4e28-8ce7-394001d188f0</variableId>
        </variableLink>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>a97344e7-5f9c-4936-92a2-d85e5463f3c9</variableId>
        </variableLink>
    </testCaseLink>
    <testCaseLink>
        <guid>489c3d69-5368-48dc-a030-5341ea10eb88</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Common Test Cases/Verify the user can upload a profile picture in supported file formats (e.g., JPG, PNG,JPE)</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>0be9b841-bf32-4f9b-82bc-05754494fc61</variableId>
        </variableLink>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>c1268245-bba6-47ba-ac1f-2734998919eb</variableId>
        </variableLink>
    </testCaseLink>
    <testCaseLink>
        <guid>cae35a69-a8a9-453d-8aba-ff53aed14ffa</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Common Test Cases/Verify the homepage loads within 2 seconds on a stable internet connection</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
    </testCaseLink>
    <testCaseLink>
        <guid>b068d097-16c1-4fe6-a8ef-db7ba9a61180</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Main Test Cases/Verify the user can reset their password via the Forgot Password link</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
    </testCaseLink>
    <testCaseLink>
        <guid>b8647b08-4bd9-4d7a-89b4-2a3ba2e25704</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Main Test Cases/Verify that all dropdown menus display the correct list of options</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>b9ae2020-cead-4d3a-a4f8-56cfc91e6cd6</variableId>
        </variableLink>
        <variableLink>
            <testDataLinkId></testDataLinkId>
            <type>DEFAULT</type>
            <value></value>
            <variableId>e5c0d540-2ad9-40a7-bb51-96f5c775c2cf</variableId>
        </variableLink>
    </testCaseLink>
    <testCaseLink>
        <guid>5ee468a8-585d-41dd-aced-9f2ab538a58a</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Main Test Cases/Verify the system displays an error message when incorrect password is entered</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
    </testCaseLink>
    <testCaseLink>
        <guid>1d1c664e-432e-4266-b7c1-5204cf28a8d6</guid>
        <isReuseDriver>false</isReuseDriver>
        <isRun>true</isRun>
        <testCaseId>Test Cases/Main Test Cases/Verify that clicking the Submit button without filling required fields shows validation messages</testCaseId>
        <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
    </testCaseLink>
</TestSuiteEntity>
